name: "Draft Release"

on:
  workflow_dispatch:

jobs:
  action:
    name: "Action"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: "Checkout Repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: "Checkout CI Scripts"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          repository: xpdustry/.github
          path: .xpdustry-ci
          sparse-checkout: scripts

      - name: "Setup Java 25"
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: "25"
          distribution: "temurin"

      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5

      - name: "Get And Validate Version"
        id: version
        run: |
          version="$(./gradlew properties -q --no-daemon |\
            grep '^version:' | cut -d ':' -f 2 | xargs)"
          .xpdustry-ci/scripts/version-validate.sh "$version" "false"
          echo "version=${version%-SNAPSHOT}" >> "$GITHUB_OUTPUT"

      - name: "Generate Changelog"
        run: |
          .xpdustry-ci/scripts/changelog-generate.sh \
            "$GITHUB_REPOSITORY" \
            ".GENERATED_CHANGELOG.md"

      - name: "Create Draft Release"
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        with:
          tag_name: "v${{ steps.version.outputs.version }}"
          name: "v${{ steps.version.outputs.version }} release"
          draft: true
          body_path: ".GENERATED_CHANGELOG.md"